image: ubuntu/latest
packages:
  - curl
  - unzip
sources:
  - https://git.sr.ht/~ruivieira/crystal-holst
tasks:
  - setup: |
      curl -fsSL https://crystal-lang.org/install.sh | sudo bash
  - test: |
      cd crystal-holst
      shards install
      crystal spec
      crystal spec
